/**
 * All code below was generated By Claude
 */
import { Worklets } from 'react-native-worklets-core';

// Create a shared context that exists across all threads
const context = Worklets.createContext('TrackingStore');

// Initialize the store on the context
context.runAsync(() => {
  'worklet';
  // Create a global object that persists across worklet calls
  global.__globalStore = {
    tapPosition: null,
    frameDimension: null,
    pixelData: null,
  };
});

// Getter and setter functions that can be called from any thread
export const getTapPosition = context.createRunAsync(() => {
  'worklet';
  return global.__globalStore.tapPosition;
});

export const setTapPosition = context.createRunAsync((value) => {
  'worklet';
  console.log("Set Tap Positon: ", value);
  global.__globalStore.tapPosition = value;
});

export const getFrameDimension = context.createRunAsync(() => {
  'worklet';
  return global.__globalStore.frameDimension;
});

export const setFrameDimension = context.createRunAsync((value) => {
  'worklet';
  global.__globalStore.frameDimension = value;
});

export const getPixelData = context.createRunAsync(() => {
  'worklet';
  return global.__globalStore.pixelData;
});

export const setPixelData = context.createRunAsync((value) => {
  'worklet';

  // Ignore value, if the same
  if (global.__globalStore.pixelData === value) return;

  console.log("Setting Pixel Data: ", value);
  global.__globalStore.pixelData = value;
  
  console.log("Clearing Tap Position");
  setTapPosition(null);
});

// Export the context if you need direct access
export default context;